"""IAM domain: users, roles, two-level role assignment, sessions. Framework-free."""

from pharmacy_os.modules.iam.domain.entities import (
    ActivationStatus,
    Branch,
    RefreshSession,
    Role,
    RoleAssignment,
    Tenant,
    User,
)
from pharmacy_os.modules.iam.domain.events import RolesChanged, UserDeactivated, UserRegistered
from pharmacy_os.modules.iam.domain.exceptions import (
    BranchNotAccessibleError,
    BranchRequiredError,
    IamError,
    InvalidCredentialsError,
    InvalidRoleError,
    InvalidTenantError,
    InvalidUserError,
    RefreshTokenInvalidError,
    RefreshTokenReusedError,
    UserInactiveError,
    UserLockedError,
    WeakPasswordError,
)
from pharmacy_os.modules.iam.domain.policy import (
    LOCKOUT_MINUTES,
    MAX_FAILED_LOGINS,
    MIN_PASSWORD_LENGTH,
    accessible_branch_ids,
    assignments_for_branch,
    is_branch_accessible,
    resolve_permissions,
    validate_password_strength,
)
from pharmacy_os.modules.iam.domain.ports import (
    BranchRepository,
    RefreshTokenRepository,
    RoleAssignmentRepository,
    RoleRepository,
    TenantRepository,
    UserRepository,
)
from pharmacy_os.modules.iam.domain.system_roles import (
    ALL_PERMISSIONS,
    BRANCH_PHARMACIST,
    CASHIER,
    CHAIN_PHARMACIST,
    SYSTEM_ADMIN,
    SYSTEM_ROLES,
    SYSTEM_ROLES_BY_CODE,
    WAREHOUSE,
    SystemRoleSpec,
)

__all__ = [
    "ALL_PERMISSIONS",
    "BRANCH_PHARMACIST",
    "CASHIER",
    "CHAIN_PHARMACIST",
    "LOCKOUT_MINUTES",
    "MAX_FAILED_LOGINS",
    "MIN_PASSWORD_LENGTH",
    "SYSTEM_ADMIN",
    "SYSTEM_ROLES",
    "SYSTEM_ROLES_BY_CODE",
    "WAREHOUSE",
    "ActivationStatus",
    "Branch",
    "BranchNotAccessibleError",
    "BranchRepository",
    "BranchRequiredError",
    "IamError",
    "InvalidCredentialsError",
    "InvalidRoleError",
    "InvalidTenantError",
    "InvalidUserError",
    "RefreshSession",
    "RefreshTokenInvalidError",
    "RefreshTokenRepository",
    "RefreshTokenReusedError",
    "Role",
    "RoleAssignment",
    "RoleAssignmentRepository",
    "RoleRepository",
    "RolesChanged",
    "SystemRoleSpec",
    "Tenant",
    "TenantRepository",
    "User",
    "UserDeactivated",
    "UserInactiveError",
    "UserLockedError",
    "UserRegistered",
    "UserRepository",
    "WeakPasswordError",
    "accessible_branch_ids",
    "assignments_for_branch",
    "is_branch_accessible",
    "resolve_permissions",
    "validate_password_strength",
]
