"""Sales domain: POS orders, payments, returns and the Rx rule. Framework-free."""

from pharmacy_os.modules.sales.domain.entities import (
    Payment,
    PaymentMethod,
    SaleLine,
    SalesOrder,
    SaleStatus,
)
from pharmacy_os.modules.sales.domain.events import SaleCompleted, SaleReturned, SoldItem
from pharmacy_os.modules.sales.domain.exceptions import (
    AllergyAcknowledgementRequiredError,
    EmptyOrderError,
    InvalidOrderStateError,
    InvalidPrescriptionRefError,
    InvalidReturnError,
    PrescriptionRequiredError,
    SalesError,
    UnderpaidError,
)
from pharmacy_os.modules.sales.domain.ports import (
    CustomerAllergy,
    CustomerAllergyProfile,
    CustomerAllergyProvider,
    DrugInfo,
    DrugInfoProvider,
    DrugSalesAggRow,
    OrderRevenueRow,
    PrescriptionInfo,
    PrescriptionInfoProvider,
    SalesOrderListRow,
    SalesRepository,
)
from pharmacy_os.modules.sales.domain.rules import (
    AllergyConflict,
    ensure_allergy_acknowledged,
    ensure_prescription_valid_for_sale,
    ensure_rx_for_etc,
    find_allergy_conflicts,
)

__all__ = [
    "Payment",
    "PaymentMethod",
    "SaleLine",
    "SalesOrder",
    "SaleStatus",
    "SaleCompleted",
    "SaleReturned",
    "SoldItem",
    "AllergyAcknowledgementRequiredError",
    "EmptyOrderError",
    "InvalidOrderStateError",
    "InvalidPrescriptionRefError",
    "InvalidReturnError",
    "PrescriptionRequiredError",
    "SalesError",
    "UnderpaidError",
    "SalesRepository",
    "OrderRevenueRow",
    "SalesOrderListRow",
    "DrugSalesAggRow",
    "CustomerAllergy",
    "CustomerAllergyProfile",
    "CustomerAllergyProvider",
    "DrugInfo",
    "DrugInfoProvider",
    "PrescriptionInfo",
    "PrescriptionInfoProvider",
    "AllergyConflict",
    "ensure_allergy_acknowledged",
    "ensure_prescription_valid_for_sale",
    "ensure_rx_for_etc",
    "find_allergy_conflicts",
]
