"""catalog and inventory tables

Revision ID: 0002_catalog_inventory
Revises: 0001_enable_extensions
Create Date: 2026-07-21
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_catalog_inventory"
down_revision: str | None = "0001_enable_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atc_codes",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "drugs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rx_class", sa.String(length=16), nullable=False),
        sa.Column("base_unit", sa.String(length=32), nullable=False),
        sa.Column("registration_no", sa.String(length=64), nullable=True),
        sa.Column("atc_code", sa.String(length=16), nullable=True),
        sa.Column("form", sa.String(length=64), nullable=True),
        sa.Column("strength", sa.String(length=64), nullable=True),
        sa.Column("barcode", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drugs_atc_code"), "drugs", ["atc_code"], unique=False)
    op.create_index(op.f("ix_drugs_barcode"), "drugs", ["barcode"], unique=False)
    op.create_index(op.f("ix_drugs_tenant_id"), "drugs", ["tenant_id"], unique=False)
    op.create_table(
        "product_batches",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("lot_no", sa.String(length=64), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("mfg_date", sa.Date(), nullable=True),
        sa.Column("cost_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("quantity_received", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drug_id", "branch_id", "lot_no", name="uq_batch_lot"),
    )
    op.create_index(
        op.f("ix_product_batches_branch_id"), "product_batches", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_batches_drug_id"), "product_batches", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_batches_expiry_date"), "product_batches", ["expiry_date"], unique=False
    )
    op.create_index(
        op.f("ix_product_batches_tenant_id"), "product_batches", ["tenant_id"], unique=False
    )
    op.create_table(
        "stock_balances",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drug_id", "batch_id", "branch_id", name="uq_balance_batch"),
    )
    op.create_index(
        op.f("ix_stock_balances_batch_id"), "stock_balances", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_balances_branch_id"), "stock_balances", ["branch_id"], unique=False
    )
    op.create_index(op.f("ix_stock_balances_drug_id"), "stock_balances", ["drug_id"], unique=False)
    op.create_index(
        op.f("ix_stock_balances_tenant_id"), "stock_balances", ["tenant_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("ref_type", sa.String(length=32), nullable=True),
        sa.Column("ref_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_movements_batch_id"), "stock_movements", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_branch_id"), "stock_movements", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_drug_id"), "stock_movements", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_movements_tenant_id"), "stock_movements", ["tenant_id"], unique=False
    )
    op.create_table(
        "drug_units",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("unit_name", sa.String(length=32), nullable=False),
        sa.Column("factor", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("is_sellable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["drug_id"], ["drugs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drug_units_drug_id"), "drug_units", ["drug_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drug_units_drug_id"), table_name="drug_units")
    op.drop_table("drug_units")
    op.drop_index(op.f("ix_stock_movements_tenant_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_drug_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_branch_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_batch_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_stock_balances_tenant_id"), table_name="stock_balances")
    op.drop_index(op.f("ix_stock_balances_drug_id"), table_name="stock_balances")
    op.drop_index(op.f("ix_stock_balances_branch_id"), table_name="stock_balances")
    op.drop_index(op.f("ix_stock_balances_batch_id"), table_name="stock_balances")
    op.drop_table("stock_balances")
    op.drop_index(op.f("ix_product_batches_tenant_id"), table_name="product_batches")
    op.drop_index(op.f("ix_product_batches_expiry_date"), table_name="product_batches")
    op.drop_index(op.f("ix_product_batches_drug_id"), table_name="product_batches")
    op.drop_index(op.f("ix_product_batches_branch_id"), table_name="product_batches")
    op.drop_table("product_batches")
    op.drop_index(op.f("ix_drugs_tenant_id"), table_name="drugs")
    op.drop_index(op.f("ix_drugs_barcode"), table_name="drugs")
    op.drop_index(op.f("ix_drugs_atc_code"), table_name="drugs")
    op.drop_table("drugs")
    op.drop_table("atc_codes")
    # ### end Alembic commands ###
