"""sales tables

Revision ID: 0003_sales
Revises: 0002_catalog_inventory
Create Date: 2026-07-21
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_sales"
down_revision: str | None = "0002_catalog_inventory"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sales_orders",
        sa.Column("client_uuid", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("prescription_ref", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "client_uuid", name="uq_sale_client_uuid"),
    )
    op.create_index(op.f("ix_sales_orders_branch_id"), "sales_orders", ["branch_id"], unique=False)
    op.create_index(op.f("ix_sales_orders_tenant_id"), "sales_orders", ["tenant_id"], unique=False)
    op.create_table(
        "sale_lines",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("requires_prescription", sa.Boolean(), nullable=False),
        sa.Column("returned_quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["sales_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sale_lines_drug_id"), "sale_lines", ["drug_id"], unique=False)
    op.create_index(op.f("ix_sale_lines_order_id"), "sale_lines", ["order_id"], unique=False)
    op.create_table(
        "sale_payments",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["sales_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sale_payments_order_id"), "sale_payments", ["order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sale_payments_order_id"), table_name="sale_payments")
    op.drop_table("sale_payments")
    op.drop_index(op.f("ix_sale_lines_order_id"), table_name="sale_lines")
    op.drop_index(op.f("ix_sale_lines_drug_id"), table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index(op.f("ix_sales_orders_tenant_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_branch_id"), table_name="sales_orders")
    op.drop_table("sales_orders")
    # ### end Alembic commands ###
