"""prescription tables

Revision ID: 0004_prescription
Revises: 0003_sales
Create Date: 2026-07-21 05:15:40.263147+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_prescription"
down_revision: str | None = "0003_sales"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prescriptions",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("doctor_name", sa.String(length=200), nullable=False),
        sa.Column("doctor_license", sa.String(length=64), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("validated_by", sa.Uuid(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescriptions_branch_id"), "prescriptions", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_customer_id"), "prescriptions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescriptions_tenant_id"), "prescriptions", ["tenant_id"], unique=False
    )
    op.create_table(
        "prescription_items",
        sa.Column("prescription_id", sa.Uuid(), nullable=False),
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("dose", sa.String(length=200), nullable=False),
        sa.Column("frequency", sa.String(length=200), nullable=False),
        sa.Column("duration", sa.String(length=200), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["prescription_id"], ["prescriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prescription_items_drug_id"), "prescription_items", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_prescription_items_prescription_id"),
        "prescription_items",
        ["prescription_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prescription_items_prescription_id"), table_name="prescription_items")
    op.drop_index(op.f("ix_prescription_items_drug_id"), table_name="prescription_items")
    op.drop_table("prescription_items")
    op.drop_index(op.f("ix_prescriptions_tenant_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_customer_id"), table_name="prescriptions")
    op.drop_index(op.f("ix_prescriptions_branch_id"), table_name="prescriptions")
    op.drop_table("prescriptions")
    # ### end Alembic commands ###
