"""compliance

Revision ID: 0005_compliance
Revises: 0004_prescription
Create Date: 2026-07-21 09:57:17.290684+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005_compliance"
down_revision: str | None = "0004_prescription"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "controlled_ledger_entries",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("lot_no", sa.String(length=64), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("transaction_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_or_destination", sa.String(length=255), nullable=False),
        sa.Column("document_no", sa.String(length=64), nullable=False),
        sa.Column("prescription_code", sa.String(length=64), nullable=True),
        sa.Column("customer_name", sa.String(length=255), nullable=True),
        sa.Column("customer_address", sa.String(length=500), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_controlled_ledger_entries_branch_id"),
        "controlled_ledger_entries",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_controlled_ledger_entries_drug_id"),
        "controlled_ledger_entries",
        ["drug_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_controlled_ledger_entries_tenant_id"),
        "controlled_ledger_entries",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "tenant_compliance_configs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("ma_co_so_ban_le", sa.String(length=12), nullable=False),
        sa.Column("ma_co_so_ban_buon", sa.String(length=12), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_tenant_compliance_configs_tenant"),
    )
    op.create_index(
        op.f("ix_tenant_compliance_configs_tenant_id"),
        "tenant_compliance_configs",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_drugs_tenant_registration_no", "drugs", ["tenant_id", "registration_no"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_drugs_tenant_registration_no", "drugs", type_="unique")
    op.drop_index(
        op.f("ix_tenant_compliance_configs_tenant_id"), table_name="tenant_compliance_configs"
    )
    op.drop_table("tenant_compliance_configs")
    op.drop_index(
        op.f("ix_controlled_ledger_entries_tenant_id"), table_name="controlled_ledger_entries"
    )
    op.drop_index(
        op.f("ix_controlled_ledger_entries_drug_id"), table_name="controlled_ledger_entries"
    )
    op.drop_index(
        op.f("ix_controlled_ledger_entries_branch_id"), table_name="controlled_ledger_entries"
    )
    op.drop_table("controlled_ledger_entries")
    # ### end Alembic commands ###
