"""national sync log

Revision ID: 0006_national_sync_log
Revises: 0005_compliance
Create Date: 2026-07-21 10:32:04.272420+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_national_sync_log"
down_revision: str | None = "0005_compliance"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "national_sync_logs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("payload_type", sa.String(length=16), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("client_uuid", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("request_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_code", sa.String(length=16), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "client_uuid", name="uq_national_sync_logs_client_uuid"),
    )
    op.create_index(
        op.f("ix_national_sync_logs_tenant_id"), "national_sync_logs", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_national_sync_logs_tenant_id"), table_name="national_sync_logs")
    op.drop_table("national_sync_logs")
    # ### end Alembic commands ###
