"""clinical

Revision ID: 0007_clinical
Revises: 0006_national_sync_log
Create Date: 2026-07-21 22:35:33.312612+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007_clinical"
down_revision: str | None = "0006_national_sync_log"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_recommendations",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("context_type", sa.String(length=8), nullable=False),
        sa.Column("context_id", sa.Uuid(), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("accepted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_recommendations_tenant_id"), "ai_recommendations", ["tenant_id"], unique=False
    )
    op.create_table(
        "drug_interactions",
        sa.Column("ingredient_a", sa.String(length=255), nullable=False),
        sa.Column("ingredient_b", sa.String(length=255), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("mechanism", sa.Text(), nullable=False),
        sa.Column("management", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ingredient_a", "ingredient_b", name="uq_drug_interactions_pair"),
    )
    op.create_index(
        op.f("ix_drug_interactions_ingredient_a"),
        "drug_interactions",
        ["ingredient_a"],
        unique=False,
    )
    op.create_index(
        op.f("ix_drug_interactions_ingredient_b"),
        "drug_interactions",
        ["ingredient_b"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drug_interactions_ingredient_b"), table_name="drug_interactions")
    op.drop_index(op.f("ix_drug_interactions_ingredient_a"), table_name="drug_interactions")
    op.drop_table("drug_interactions")
    op.drop_index(op.f("ix_ai_recommendations_tenant_id"), table_name="ai_recommendations")
    op.drop_table("ai_recommendations")
    # ### end Alembic commands ###
