"""catalog_ingredients

Revision ID: 0008_catalog_ingredients
Revises: 0007_clinical
Create Date: 2026-07-22 05:09:20.494724+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008_catalog_ingredients"
down_revision: str | None = "0007_clinical"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "active_ingredients",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_active_ingredients_name"),
    )
    op.create_table(
        "drug_ingredients",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["drug_id"], ["drugs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ingredient_id"], ["active_ingredients.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_ingredients_drug_id"), "drug_ingredients", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_drug_ingredients_ingredient_id"),
        "drug_ingredients",
        ["ingredient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drug_ingredients_ingredient_id"), table_name="drug_ingredients")
    op.drop_index(op.f("ix_drug_ingredients_drug_id"), table_name="drug_ingredients")
    op.drop_table("drug_ingredients")
    op.drop_table("active_ingredients")
    # ### end Alembic commands ###
