"""crm_customers

Revision ID: 0009_crm_customers
Revises: 0008_catalog_ingredients
Create Date: 2026-07-22 05:38:37.081840+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0009_crm_customers"
down_revision: str | None = "0008_catalog_ingredients"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("dob", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=16), nullable=True),
        sa.Column("weight_kg", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("national_id_hash", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customers_phone"), "customers", ["phone"], unique=False)
    op.create_index(op.f("ix_customers_tenant_id"), "customers", ["tenant_id"], unique=False)
    op.create_table(
        "customer_allergies",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["active_ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_allergies_customer_id"),
        "customer_allergies",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_allergies_ingredient_id"),
        "customer_allergies",
        ["ingredient_id"],
        unique=False,
    )
    op.create_table(
        "customer_conditions",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("condition_code", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_conditions_customer_id"),
        "customer_conditions",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "customer_medication_history",
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("ref_id", sa.Uuid(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_medication_history_customer_id"),
        "customer_medication_history",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_medication_history_drug_id"),
        "customer_medication_history",
        ["drug_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_medication_history_ref_id"),
        "customer_medication_history",
        ["ref_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_customer_medication_history_ref_id"), table_name="customer_medication_history"
    )
    op.drop_index(
        op.f("ix_customer_medication_history_drug_id"), table_name="customer_medication_history"
    )
    op.drop_index(
        op.f("ix_customer_medication_history_customer_id"), table_name="customer_medication_history"
    )
    op.drop_table("customer_medication_history")
    op.drop_index(op.f("ix_customer_conditions_customer_id"), table_name="customer_conditions")
    op.drop_table("customer_conditions")
    op.drop_index(op.f("ix_customer_allergies_ingredient_id"), table_name="customer_allergies")
    op.drop_index(op.f("ix_customer_allergies_customer_id"), table_name="customer_allergies")
    op.drop_table("customer_allergies")
    op.drop_index(op.f("ix_customers_tenant_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_phone"), table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
