"""clinical_tenant_ai_settings

Revision ID: 0010_clinical_tenant_ai_settings
Revises: 0009_crm_customers
Create Date: 2026-07-22 06:14:28.635391+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010_clinical_tenant_ai_settings"
down_revision: str | None = "0009_crm_customers"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_ai_settings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("enable_clinical_ai", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", name="uq_tenant_ai_settings_tenant"),
    )
    op.create_index(
        op.f("ix_tenant_ai_settings_tenant_id"), "tenant_ai_settings", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenant_ai_settings_tenant_id"), table_name="tenant_ai_settings")
    op.drop_table("tenant_ai_settings")
    # ### end Alembic commands ###
