"""procurement

Revision ID: 0011_procurement
Revises: 0010_clinical_tenant_ai_settings
Create Date: 2026-07-22 14:10:19.926384+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_procurement"
down_revision: str | None = "0010_clinical_tenant_ai_settings"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goods_receipts",
        sa.Column("po_id", sa.Uuid(), nullable=False),
        sa.Column("received_by", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goods_receipts_branch_id"), "goods_receipts", ["branch_id"], unique=False
    )
    op.create_index(op.f("ix_goods_receipts_po_id"), "goods_receipts", ["po_id"], unique=False)
    op.create_index(
        op.f("ix_goods_receipts_tenant_id"), "goods_receipts", ["tenant_id"], unique=False
    )
    op.create_table(
        "purchase_orders",
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("ordered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_orders_branch_id"), "purchase_orders", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"), "purchase_orders", ["supplier_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_orders_tenant_id"), "purchase_orders", ["tenant_id"], unique=False
    )
    op.create_table(
        "suppliers",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("tax_code", sa.String(length=32), nullable=True),
        sa.Column("contact_name", sa.String(length=200), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suppliers_tenant_id"), "suppliers", ["tenant_id"], unique=False)
    op.create_table(
        "purchase_order_items",
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_ordered", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("quantity_received", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["purchase_order_id"], ["purchase_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchase_order_items_drug_id"), "purchase_order_items", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_purchase_order_items_purchase_order_id"),
        "purchase_order_items",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "goods_receipt_items",
        sa.Column("goods_receipt_id", sa.Uuid(), nullable=False),
        sa.Column("po_item_id", sa.Uuid(), nullable=False),
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_received", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("lot_no", sa.String(length=64), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("mfg_date", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["goods_receipt_id"], ["goods_receipts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["po_item_id"],
            ["purchase_order_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goods_receipt_items_drug_id"), "goods_receipt_items", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_goods_receipt_items_goods_receipt_id"),
        "goods_receipt_items",
        ["goods_receipt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_receipt_items_po_item_id"),
        "goods_receipt_items",
        ["po_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goods_receipt_items_po_item_id"), table_name="goods_receipt_items")
    op.drop_index(op.f("ix_goods_receipt_items_goods_receipt_id"), table_name="goods_receipt_items")
    op.drop_index(op.f("ix_goods_receipt_items_drug_id"), table_name="goods_receipt_items")
    op.drop_table("goods_receipt_items")
    op.drop_index(
        op.f("ix_purchase_order_items_purchase_order_id"), table_name="purchase_order_items"
    )
    op.drop_index(op.f("ix_purchase_order_items_drug_id"), table_name="purchase_order_items")
    op.drop_table("purchase_order_items")
    op.drop_index(op.f("ix_suppliers_tenant_id"), table_name="suppliers")
    op.drop_table("suppliers")
    op.drop_index(op.f("ix_purchase_orders_tenant_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_branch_id"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    op.drop_index(op.f("ix_goods_receipts_tenant_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_po_id"), table_name="goods_receipts")
    op.drop_index(op.f("ix_goods_receipts_branch_id"), table_name="goods_receipts")
    op.drop_table("goods_receipts")
    # ### end Alembic commands ###
