"""stock_reconciliation

Revision ID: 0012_stock_reconciliation
Revises: 0011_procurement
Create Date: 2026-07-22 15:09:59.288597+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012_stock_reconciliation"
down_revision: str | None = "0011_procurement"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_reconciliation_needed",
        sa.Column("grn_id", sa.Uuid(), nullable=False),
        sa.Column("po_item_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_reconciliation_needed_branch_id"),
        "stock_reconciliation_needed",
        ["branch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_reconciliation_needed_grn_id"),
        "stock_reconciliation_needed",
        ["grn_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_reconciliation_needed_tenant_id"),
        "stock_reconciliation_needed",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_reconciliation_needed_tenant_id"), table_name="stock_reconciliation_needed"
    )
    op.drop_index(
        op.f("ix_stock_reconciliation_needed_grn_id"), table_name="stock_reconciliation_needed"
    )
    op.drop_index(
        op.f("ix_stock_reconciliation_needed_branch_id"), table_name="stock_reconciliation_needed"
    )
    op.drop_table("stock_reconciliation_needed")
    # ### end Alembic commands ###
