"""sales_order_customer_id

Revision ID: 0016_sales_order_customer_id
Revises: 0015_customer_consents
Create Date: 2026-07-23 20:13:47.366448+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0016_sales_order_customer_id"
down_revision: str | None = "0015_customer_consents"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sales_orders", sa.Column("customer_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_sales_orders_customer_id"), "sales_orders", ["customer_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_orders_customer_id"), table_name="sales_orders")
    op.drop_column("sales_orders", "customer_id")
    # ### end Alembic commands ###
