"""ai_recommendation_context_index

Revision ID: 0018_ai_rec_context_idx
Revises: 0017_event_outbox
Create Date: 2026-07-24 07:07:11.736239+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0018_ai_rec_context_idx"
down_revision: str | None = "0017_event_outbox"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_ai_recommendations_context",
        "ai_recommendations",
        ["tenant_id", "context_type", "context_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_recommendations_context", table_name="ai_recommendations")
    # ### end Alembic commands ###
