"""event_outbox_retention_index

Revision ID: 0019_outbox_retention_idx
Revises: 0018_ai_rec_context_idx
Create Date: 2026-07-24 09:00:36.565893+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0019_outbox_retention_idx"
down_revision: str | None = "0018_ai_rec_context_idx"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_event_outbox_retention", "event_outbox", ["status", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_outbox_retention", table_name="event_outbox")
    # ### end Alembic commands ###
