"""sales_order_sold_by_user_id

Revision ID: 0021_sales_order_sold_by
Revises: 0020_audit_target_type_idx
Create Date: 2026-07-25 02:39:14.699488+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0021_sales_order_sold_by"
down_revision: str | None = "0020_audit_target_type_idx"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sales_orders", sa.Column("sold_by_user_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_sales_orders_sold_by_user_id"),
        "sales_orders",
        ["sold_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sales_orders_sold_by_user_id"), table_name="sales_orders")
    op.drop_column("sales_orders", "sold_by_user_id")
    # ### end Alembic commands ###
