"""consent basis

Revision ID: 661017d090ba
Revises: 0037_drugs_sale_price
Create Date: 2026-07-29 10:21:39.221531+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0038_consent_basis"
down_revision: str | None = "0037_drugs_sale_price"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 🔴 `server_default='EXPLICIT'` cho dòng CŨ, và đó là lựa chọn có chủ đích
    # chứ không phải giá trị cho có: mọi dòng ghi trước 2026-07-29 đều được lấy
    # bằng cách nhân viên bấm trên bảng đồng ý, vì lúc đó **không tồn tại** cách
    # nào khác. Điền "COUNTER" cho chúng là tự khai một nguồn gốc chưa ai kiểm
    # chứng — đúng thứ trường này sinh ra để tránh.
    op.add_column(
        "customer_consents",
        sa.Column("basis", sa.String(length=16), server_default="EXPLICIT", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customer_consents", "basis")
    # ### end Alembic commands ###
