"""drug_price_history

Revision ID: 0039_drug_price_history
Revises: 0038_consent_basis
Create Date: 2026-07-31 01:57:52.606898+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0039_drug_price_history"
down_revision: str | None = "0038_consent_basis"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drug_price_history",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("new_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drug_id"],
            ["drugs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drug_price_history_drug_id"), "drug_price_history", ["drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_drug_price_history_tenant_id"), "drug_price_history", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drug_price_history_tenant_id"), table_name="drug_price_history")
    op.drop_index(op.f("ix_drug_price_history_drug_id"), table_name="drug_price_history")
    op.drop_table("drug_price_history")
    # ### end Alembic commands ###
