"""anh don thuoc luu trong CSDL

``image_data`` khai bằng ``sa.Text()`` chứ không phải ``EncryptedText``: mã hoá xảy ra ở
tầng Python (``TypeDecorator``), CSDL chỉ thấy ``text``. Cùng khuôn 0030_encrypt_compliance_pii.
Autogenerate sinh ra tham chiếu ``pharmacy_os.core.db.encrypted_types.EncryptedText`` mà
không nhập gì — migration ném ``NameError`` ngay lần chạy đầu. Sửa tay là đúng, không phải
thêm import: một migration KHÔNG nên phụ thuộc vào mã ứng dụng, vì nó phải chạy lại được
trên một cây mã tương lai đã đổi.

Revision ID: 0040_rx_image
Revises: 0039_drug_price_history
Create Date: 2026-07-31 06:16:01.383563+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0040_rx_image"
down_revision: str | None = "0039_drug_price_history"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prescriptions",
        sa.Column("image_data", sa.Text(), nullable=True),
    )
    op.add_column(
        "prescriptions", sa.Column("image_content_type", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prescriptions", "image_content_type")
    op.drop_column("prescriptions", "image_data")
    # ### end Alembic commands ###
