"""don tu anh khong bat buoc khach

Revision ID: 0041_rx_customer_nullable
Revises: 0040_rx_image
Create Date: 2026-07-31 07:37:57.576366+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0041_rx_customer_nullable"
down_revision: str | None = "0040_rx_image"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prescriptions", "customer_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prescriptions", "customer_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
