"""ton theo vi tri + 2 cot vi tri tren stock_movements

Revision ID: 0043_stock_at_location
Revises: 0042_locations
Create Date: 2026-07-31 12:25:38.681438+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0043_stock_at_location"
down_revision: str | None = "0042_locations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_at_location",
        sa.Column("drug_id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "batch_id", "location_id", name="uq_stock_at_location"),
    )
    op.create_index(
        op.f("ix_stock_at_location_batch_id"), "stock_at_location", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_at_location_branch_id"), "stock_at_location", ["branch_id"], unique=False
    )
    op.create_index(
        "ix_stock_at_location_drug", "stock_at_location", ["branch_id", "drug_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_at_location_drug_id"), "stock_at_location", ["drug_id"], unique=False
    )
    op.create_index(
        "ix_stock_at_location_loc", "stock_at_location", ["branch_id", "location_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_at_location_tenant_id"), "stock_at_location", ["tenant_id"], unique=False
    )
    op.add_column("stock_movements", sa.Column("from_location_id", sa.Uuid(), nullable=True))
    op.add_column("stock_movements", sa.Column("to_location_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stock_movements", "to_location_id")
    op.drop_column("stock_movements", "from_location_id")
    op.drop_index(op.f("ix_stock_at_location_tenant_id"), table_name="stock_at_location")
    op.drop_index("ix_stock_at_location_loc", table_name="stock_at_location")
    op.drop_index(op.f("ix_stock_at_location_drug_id"), table_name="stock_at_location")
    op.drop_index("ix_stock_at_location_drug", table_name="stock_at_location")
    op.drop_index(op.f("ix_stock_at_location_branch_id"), table_name="stock_at_location")
    op.drop_index(op.f("ix_stock_at_location_batch_id"), table_name="stock_at_location")
    op.drop_table("stock_at_location")
    # ### end Alembic commands ###
