"""nguoi chot don hang chiu trach nhiem luu don thuoc

Revision ID: 0044_rx_created_by
Revises: 0043_stock_at_location
Create Date: 2026-07-31 14:13:42.207029+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0044_rx_created_by"
down_revision: str | None = "0043_stock_at_location"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prescriptions", sa.Column("created_by", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prescriptions", "created_by")
    # ### end Alembic commands ###
