"""Compliance domain: national drug record, controlled-substance ledger, national-DB
sync log/gateway, converter helpers for QĐ540/TT20/2017/QĐ1867. Framework-free.
"""

from pharmacy_os.modules.compliance.domain.converters import (
    to_qld_code,
    to_qld_date,
    to_qld_datetime,
)
from pharmacy_os.modules.compliance.domain.entities import (
    ControlledLedgerEntry,
    ControlledSubstance,
    ControlledSubstanceAppendix,
    ControlledSubstanceCategory,
    CustomerDetail,
    DrugReturnRecord,
    LedgerBookSignature,
    LedgerBookType,
    LedgerDirection,
    NationalDrugRecord,
    NationalSyncLog,
    ReturnedDrugItem,
    SyncPayloadType,
    SyncStatus,
    TenantComplianceConfig,
    book_type_for,
)
from pharmacy_os.modules.compliance.domain.exceptions import (
    ComplianceError,
    InvalidSyncStateError,
    MissingControlledCustomerDetailError,
    MissingControlledPrescriptionCodeError,
    MissingEtcPrescriptionFieldsError,
    NotControlledSubstanceError,
)
from pharmacy_os.modules.compliance.domain.ports import (
    ControlledLedgerRepository,
    DrugMasterFacts,
    DrugMasterProvider,
    DrugReturnRecordRepository,
    LedgerBookSignatureRepository,
    LedgerPeriodAggregate,
    NationalDrugDbGateway,
    NationalSyncLogRepository,
    SigningReauthProvider,
    SyncAck,
    SyncRequest,
    TenantComplianceConfigRepository,
)
from pharmacy_os.modules.compliance.domain.rules import (
    EtcPrescriptionPolicy,
    validate_controlled_sale,
    validate_etc_sale,
)

__all__ = [
    "to_qld_code",
    "to_qld_date",
    "to_qld_datetime",
    "ControlledLedgerEntry",
    "ControlledSubstance",
    "ControlledSubstanceAppendix",
    "ControlledSubstanceCategory",
    "CustomerDetail",
    "DrugReturnRecord",
    "LedgerBookSignature",
    "LedgerBookType",
    "LedgerDirection",
    "book_type_for",
    "NationalDrugRecord",
    "NationalSyncLog",
    "ReturnedDrugItem",
    "SyncPayloadType",
    "SyncStatus",
    "TenantComplianceConfig",
    "ComplianceError",
    "InvalidSyncStateError",
    "MissingControlledCustomerDetailError",
    "MissingControlledPrescriptionCodeError",
    "MissingEtcPrescriptionFieldsError",
    "NotControlledSubstanceError",
    "ControlledLedgerRepository",
    "DrugMasterFacts",
    "DrugReturnRecordRepository",
    "LedgerBookSignatureRepository",
    "LedgerPeriodAggregate",
    "DrugMasterProvider",
    "NationalDrugDbGateway",
    "NationalSyncLogRepository",
    "SigningReauthProvider",
    "SyncAck",
    "SyncRequest",
    "TenantComplianceConfigRepository",
    "EtcPrescriptionPolicy",
    "validate_controlled_sale",
    "validate_etc_sale",
]
