"""Inventory domain: batches, event-sourced movements, FEFO. Framework-free."""

from pharmacy_os.modules.inventory.domain.entities import (
    MovementType,
    ProductBatch,
    StockMovement,
    StockReconciliationNeeded,
)
from pharmacy_os.modules.inventory.domain.events import (
    LowStockDetected,
    StockMovedIn,
    StockMovedOut,
    StockShortfallDetected,
)
from pharmacy_os.modules.inventory.domain.exceptions import (
    DuplicateMovementError,
    InsufficientStockError,
    LotExpiryMismatchError,
    ReconciliationAlreadyResolvedError,
)
from pharmacy_os.modules.inventory.domain.fefo import Allocation, BatchAvailability, allocate_fefo
from pharmacy_os.modules.inventory.domain.ports import (
    BalanceRepository,
    BatchRepository,
    BatchStockRow,
    DrugOnHandRow,
    LocationInfo,
    LocationInfoProvider,
    LocationStockRow,
    MovementRepository,
    StockAtLocationRepository,
    StockCountRepository,
    StockReconciliationRepository,
    TomTatO,
)
from pharmacy_os.modules.inventory.domain.putaway import (
    ChangLay,
    ExceedsBatchOnHandError,
    LocationNotUsableError,
    LocationStock,
    PickCandidate,
    PutAwayError,
    allocate_from_locations,
    chua_xep_o,
    ensure_can_put_away,
    gom_lo_trinh,
    sort_pick_candidates,
)

__all__ = [
    "LocationInfo",
    "LocationInfoProvider",
    "LocationStockRow",
    "StockAtLocationRepository",
    "TomTatO",
    "StockCountRepository",
    "ExceedsBatchOnHandError",
    "LocationNotUsableError",
    "LocationStock",
    "ChangLay",
    "PickCandidate",
    "PutAwayError",
    "allocate_from_locations",
    "gom_lo_trinh",
    "chua_xep_o",
    "ensure_can_put_away",
    "sort_pick_candidates",
    "MovementType",
    "ProductBatch",
    "StockMovement",
    "StockReconciliationNeeded",
    "StockMovedIn",
    "StockMovedOut",
    "LowStockDetected",
    "StockShortfallDetected",
    "DuplicateMovementError",
    "InsufficientStockError",
    "LotExpiryMismatchError",
    "ReconciliationAlreadyResolvedError",
    "Allocation",
    "BatchAvailability",
    "allocate_fefo",
    "BatchRepository",
    "BatchStockRow",
    "DrugOnHandRow",
    "MovementRepository",
    "BalanceRepository",
    "StockReconciliationRepository",
]
